# set sao colecoes de elementos unicos, ou seja, nao permitem elementos duplicados
# sao criados usando chaves {}

planetas = {"Mercurio", "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano", "Netuno"}
print(planetas)
print(len(planetas)) # isso vai imprimir 8, pois o set planetas tem 8 elementos unicos
planetas.add("Plutao") # isso vai adicionar o elemento "Plutao" ao set planetas, pois o metodo add() adiciona um elemento ao set. O set planetas agora tem 9 elementos unicos, incluindo "Plutao".
print(planetas) 

for astro in planetas:
    print(astro.upper()) # isso vai imprimir cada elemento do set planetas em uma linha diferente, convertendo cada elemento para maiusculo usando o metodo upper(). O loop for percorre cada elemento do set planetas e imprime o resultado da conversao para maiusculo. A ordem dos elementos impressos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas.    

aster = ["Sol", "Sol", "Sirius", "Betelgeuse", "Rigel", "Vega"]
print(aster)
print(aster, end=' ') # isso vai imprimir o set aster, mas sem pular para a linha seguinte, pois o argumento end="" do comando print() especifica que o final da linha deve ser uma string vazia, em vez de pular para a linha seguinte. O resultado é que o set aster sera impresso na mesma linha do prompt de comando, sem quebrar a linha. O set aster ainda sera impresso com as chaves {}, pois sets sao representados por chaves em Python. O resultado final sera algo como "{'Sol', 'Sirius', 'Betelgeuse', 'Rigel', 'Vega'}", mas tudo na mesma linha do prompt de comando.
asterset = set(aster)
print(asterset) # isso vai imprimir o set asterset, que é criado a partir da lista aster usando a funcao set(). O set asterset vai conter apenas os elementos unicos da lista aster, ou seja, "Sol", "Sirius", "Betelgeuse", "Rigel" e "Vega". O elemento "Sol" aparece duas vezes na lista aster, mas no set asterset ele aparece apenas uma vez, pois sets nao permitem elementos duplicados. O resultado final sera algo como "{'Sol', 'Sirius', 'Betelgeuse', 'Rigel', 'Vega'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas.

a = {"Mercurio", "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano", "Netuno"}
ab = {"Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano", "Netuno", "Plutao"} 
print( a | ab) # isso vai imprimir a uniao dos sets a e ab, ou seja, um set que contem todos os elementos unicos presentes em ambos os sets. O operador | é usado para calcular a uniao de dois sets. O resultado final sera algo como "{'Mercurio', 'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno', 'Plutao'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set resultante da uniao vai conter todos os planetas do sistema solar, incluindo "Plutao", que esta presente no set ab mas nao no set a.    
print(a == ab) # isso vai imprimir False, pois os sets a e ab sao diferentes, mesmo que eles tenham muitos elementos em comum. O set a nao tem o elemento "Plutao", enquanto o set ab tem o elemento "Plutao". Portanto, os dois sets nao sao iguais, e o resultado da comparacao usando o operador == é False. O operador == verifica se os dois sets sao iguais, ou seja, se eles contêm exatamente os mesmos elementos unicos, independentemente da ordem de insercao. Como os sets a e ab sao diferentes, o resultado da comparacao é False.    
print(a != ab) # isso vai imprimir True, pois os sets a e ab sao diferentes, mesmo que eles tenham muitos elementos em comum. O set a nao tem o elemento "Plutao", enquanto o set ab tem o elemento "Plutao". Portanto, os dois sets nao sao iguais, e o resultado da comparacao usando o operador != é True. O operador != verifica se os dois sets sao diferentes, ou seja, se eles nao contêm exatamente os mesmos elementos unicos, independentemente da ordem de insercao. Como os sets a e ab sao diferentes, o resultado da comparacao é True. O operador != é o oposto do operador ==, e retorna True quando os dois sets sao diferentes
print(a.union(ab)) # isso vai imprimir a uniao dos sets a e ab, ou seja, um set que contem todos os elementos unicos presentes em ambos os sets. O metodo union() é usado para calcular a uniao de dois sets. O resultado final sera algo como "{'Mercurio', 'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno', 'Plutao'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set resultante da uniao vai conter todos os planetas do sistema solar, incluindo "Plutao", que esta presente no set ab mas nao no set a. O metodo union() retorna um novo set com a uniao dos dois sets, sem modificar os sets originais.   

print(a & ab)# isso vai imprimir a intersecao dos sets a e ab, ou seja, um set que contem apenas os elementos unicos presentes em ambos os sets. O operador & é usado para calcular a intersecao de dois sets. O resultado final sera algo como "{'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set resultante da intersecao vai conter apenas os planetas do sistema solar que estao presentes em ambos os sets a e ab, ou seja, "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano" e "Netuno". O operador & retorna um novo set com a intersecao dos dois sets, sem modificar os sets originais. 
print( a.intersection(ab)) # isso vai imprimir a intersecao dos sets a e ab, ou seja, um set que contem apenas os elementos unicos presentes em ambos os sets. O operador & é usado para calcular a intersecao de dois sets. O metodo intersection() também é usado para calcular a intersecao de dois sets. O resultado final sera algo como "{'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set resultante da intersecao vai conter apenas os planetas do sistema solar que estao presentes em ambos os sets a e ab, ou seja, "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano" e "Netuno". O operador & e o metodo intersection() retornam um novo set com a intersecao dos dois sets, sem modificar os sets originais.    

print(a ^ ab)# isso vai imprimir a diferenca simetrica dos sets a e ab, ou seja, um set que contem apenas os elementos unicos presentes em um dos sets, mas nao em ambos. O operador ^ é usado para calcular a diferenca simetrica de dois sets. O resultado final sera algo como "{'Mercurio', 'Plutao'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set resultante da diferenca simetrica vai conter apenas os planetas do sistema solar que estao presentes em um dos sets a ou ab, mas nao em ambos, ou seja, "Mercurio" (presente no set a mas nao no set ab) e "Plutao" (presente no set ab mas nao no set a). O operador ^ retorna um novo set com a diferenca simetrica dos dois sets, sem modificar os sets originais.
print(a.symmetric_difference(ab)) # isso vai imprimir a diferenca simetrica dos sets a e ab, ou seja, um set que contem apenas os elementos unicos presentes em um dos sets, mas nao em ambos. O operador ^ é usado para calcular a diferenca simetrica de dois sets. O metodo symmetric_difference() também é usado para calcular a diferenca simetrica de dois sets. O resultado final sera algo como "{'Mercurio', 'Plutao'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set resultante da diferenca simetrica vai conter apenas os planetas do sistema solar que estao presentes em um dos sets a ou ab, mas nao em ambos, ou seja, "Mercurio" (presente no set a mas nao no set ab) e "Plutao" (presente no set ab mas nao no set a). O operador ^ e o metodo symmetric_difference() retornam um novo set com a diferenca simetrica dos dois sets, sem modificar os sets originais.   

a.add("Plutao") # isso vai adicionar o elemento "Plutao" ao set a, pois o metodo add() adiciona um elemento ao set. O set a agora tem 9 elementos unicos, incluindo "Plutao". O set ab ja tem o elemento "Plutao", entao agora os dois sets a e ab sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Plutao".
ab.add("Mercurio") # isso vai adicionar o elemento "Mercurio" ao set ab, pois o metodo add() adiciona um elemento ao set. O set ab agora tem 9 elementos unicos, incluindo "Mercurio". O set a ja tem o elemento "Mercurio", entao agora os dois sets a e ab sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Mercurio". Agora os sets a e ab sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Mercurio" e "Plutao". O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False.
print(a, ab)# isso vai imprimir os sets a e ab, que agora sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Mercurio" e "Plutao". O resultado final sera algo como "{'Mercurio', 'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno', 'Plutao'} {'Mercurio', 'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno', 'Plutao'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set a e o set ab agora sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Mercurio" e "Plutao". O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False.  

a.discard("Plutao") # isso vai remover o elemento "Plutao" do set a, pois o metodo discard() remove um elemento do set. O set a agora tem 8 elementos unicos, sem "Plutao". O set ab ainda tem o elemento "Plutao", entao agora os dois sets a e ab sao diferentes, pois o set a nao tem o elemento "Plutao", enquanto o set ab tem o elemento "Plutao". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True.
ab.discard("Mercurio") # isso vai remover o elemento "Mercurio" do set ab, pois o metodo discard() remove um elemento do set. O set ab agora tem 8 elementos unicos, sem "Mercurio". O set a ainda tem o elemento "Mercurio", entao agora os dois sets a e ab sao diferentes, pois o set a tem o elemento "Mercurio", enquanto o set ab nao tem o elemento "Mercurio". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True. Agora os sets a e ab sao diferentes, pois o set a tem o elemento "Mercurio", enquanto o set ab nao tem o elemento "Mercurio". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True.

print(a, ab) # isso vai imprimir os sets a e ab, que agora sao diferentes
a.remove("Plutao") # isso vai remover o elemento "Plutao" do set a, pois o metodo remove() remove um elemento do set. O set a agora tem 8 elementos unicos, sem "Plutao". O set ab ainda tem o elemento "Plutao", entao agora os dois sets a e ab sao diferentes, pois o set a nao tem o elemento "Plutao", enquanto o set ab tem o elemento "Plutao". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True.   
ab.remove("Mercurio") # isso vai remover o elemento "Mercurio" do set ab, pois o metodo remove() remove um elemento do set. O set ab agora tem 8 elementos unicos, sem "Mercurio". O set a ainda tem o elemento "Mercurio", entao agora os dois sets a e ab sao diferentes, pois o set a tem o elemento "Mercurio", enquanto o set ab nao tem o elemento "Mercurio". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True. Agora os sets a e ab sao diferentes, pois o set a tem o elemento "Mercurio", enquanto o set ab nao tem o elemento "Mercurio". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True.
print(a, ab) # isso vai imprimir os sets a e ab, que agora sao diferentes  pois o set a tem o elemento "Mercurio", enquanto o set ab nao tem o elemento "Mercurio". O resultado final sera algo como "{'Mercurio', 'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'} {'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno', 'Plutao'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set a e o set ab agora sao diferentes, pois o set a tem o elemento "Mercurio", enquanto o set ab nao tem o elemento "Mercurio". O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True.   

a.pop()
ab.pop()
# pop() remove um elemento aleatorio do set, pois sets sao colecoes nao ordenadas e nao tem indices. O resultado final sera algo como "{'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'} {'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set a e o set ab agora sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano" e "Netuno". O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False. O metodo pop() retorna o elemento removido do set, mas como o elemento removido é aleatorio, nao podemos prever qual elemento sera removido. O metodo pop() modifica o set original, removendo um elemento aleatorio do set. O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False, pois os sets a e ab agora sao iguais, contendo os mesmos elementos unicos.
print(a, ab) # isso vai imprimir os sets a e ab, que agora sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano" e "Netuno". O resultado final sera algo como "{'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'} {'Venus', 'Terra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Netuno'}", mas a ordem dos elementos pode ser diferente da ordem de insercao, pois sets sao colecoes nao ordenadas. O set a e o set ab agora sao iguais, pois ambos contêm os mesmos elementos unicos, incluindo "Venus", "Terra", "Marte", "Jupiter", "Saturno", "Urano" e "Netuno". O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False. 

a.clear() # isso vai remover todos os elementos do set a, deixando-o vazio, pois o metodo clear() remove todos os elementos do set. O set a agora é um set vazio, sem nenhum elemento. O set ab ainda tem seus elementos, entao agora os dois sets a e ab sao diferentes, pois o set a é vazio, enquanto o set ab tem seus elementos. O resultado da comparacao usando o operador == agora sera False, e o resultado da comparacao usando o operador != agora sera True.
ab.clear() # isso vai remover todos os elementos do set ab, deixando-o vazio, pois  o metodo clear() remove todos os elementos do set. O set ab agora é um set vazio, sem nenhum elemento. O set a ainda é um set vazio, entao agora os dois sets a e ab sao iguais, pois ambos sao sets vazios, sem nenhum elemento. O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False.
print(a, ab) # isso vai imprimir os sets a e ab, que agora sao iguais, pois ambos sao sets vazios, sem nenhum elemento. O resultado final sera "{} {}", indicando que ambos os sets a e ab estao vazios. O set a e o set ab agora sao iguais, pois ambos sao sets vazios, sem nenhum elemento. O resultado da comparacao usando o operador == agora sera True, e o resultado da comparacao usando o operador != agora sera False.   

